language: rust
cache: cargo
env:
- RUSTFLAGS="-Clink-arg=-fuse-ld=gold"
rust:
- nightly
script:
- cargo install --force afl
- cargo afl build
- "./ci/upload_builds.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_edc4a4aaa9a0_key -iv $encrypted_edc4a4aaa9a0_iv
  -in ci/auth.json-enc -out ci/auth.json -d
