language: rust
cache: cargo

env:
  global:
    - QUICKCHECK_GENERATOR_SIZE=10000
    - QUICKCHECK_TESTS=10000

matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo test
    - rust: stable
      script:
        - cargo test --release
    - rust: beta
      script:
        - cargo test
    - rust: beta
      script:
        - cargo test --release
    - rust: nightly
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy
        - cargo test
    - rust: nightly
      script:
        - cargo test --release
